title: Remote Sensing of Natural Hazards 
description: An introductory remote sensing course focused on natural hazards
theme: just-the-docs

url: jucardwell.github.io/remote-sensing-hazards

search_enabled: false
